[profile.default]
src = "contracts/lending"
test = "test"
out = "out"
libs = ["lib/forge-std"]
solc_version = "0.8.28"
via_ir = true
optimizer = true
optimizer_runs = 200
auto_detect_remappings = false
remappings = [
    "forge-std/=lib/forge-std/src/"
]
